### ISSUE TITLE
Panic when trying to login with Fly on Darwin

### ISSUE THREAD

**Issue by bvandewalle** [concourse/fly#159]
Hi,

There seem to be a panic when trying to login with Fly on Darwin/MacOS.

I get the panic after I enter the token manually, or after it gets discovered automatically.

```
bvandewa@sharma:CI$ ./fly -t gcp login --concourse-url https://ci.whatever.com -k
logging in to team 'main'

navigate to the following URL in your browser:

    https://ci.whatever.com/auth/github?team_name=main&fly_local_port=63407

or enter token manually: panic: assignment to entry in nil map

goroutine 1 [running]:
panic(0x42a140, 0xc42015ffb0)
	/usr/local/Cellar/go/1.7.1/libexec/src/runtime/panic.go:500 +0x1a1
github.com/concourse/fly/rc.SaveTarget(0x7fff5fbffa69, 0x3, 0x7fff5fbffa83, 0x16, 0x180001, 0x4a1a60, 0x4, 0xc420168dc0, 0x0, 0x0, ...)
	/Users/pilot/Worker/workdir/containers/00002te877v/tmp/build/a9832f70/concourse/src/github.com/concourse/fly/rc/targets.go:81 +0x1bd
github.com/concourse/fly/commands.(*LoginCommand).saveTarget(0x8e1940, 0x7fff5fbffa83, 0x16, 0xc4201498b8, 0x0, 0x0, 0x31, 0x6a5bc0)
	/Users/pilot/Worker/workdir/containers/00002te877v/tmp/build/a9832f70/concourse/src/github.com/concourse/fly/commands/login.go:291 +0x106
github.com/concourse/fly/commands.(*LoginCommand).Execute(0x8e1940, 0xc420072840, 0x0, 0x6, 0x1, 0x0)
	/Users/pilot/Worker/workdir/containers/00002te877v/tmp/build/a9832f70/concourse/src/github.com/concourse/fly/commands/login.go:152 +0x622
github.com/jessevdk/go-flags.(*Parser).ParseArgs(0xc420072780, 0xc42000c0f0, 0x6, 0x6, 0xc42001a240, 0xc420072780, 0x7fff5fbffa62, 0x0, 0x0)
	/Users/pilot/Worker/workdir/containers/00002te877v/tmp/build/a9832f70/concourse/src/github.com/jessevdk/go-flags/parser.go:314 +0x8e6
github.com/jessevdk/go-flags.(*Parser).Parse(0xc420072780, 0x8e1920, 0x6, 0xc420072780, 0xd0, 0x4e2d41)
	/Users/pilot/Worker/workdir/containers/00002te877v/tmp/build/a9832f70/concourse/src/github.com/jessevdk/go-flags/parser.go:185 +0x74
main.main()
	/Users/pilot/Worker/workdir/containers/00002te877v/tmp/build/a9832f70/concourse/src/github.com/concourse/fly/main.go:19 +0xae
```

**Comment by bvandewalle** [comment]
FYI if anyone get the same issue: I logged in with my Linux VM, then copied the ~/.flyrc over to my Darwin OS, Kind of hacky, but made the job

**Comment by devdavidkarlsson** [comment]
it works on osx for me...

**Comment by joshzarrabi** [comment]
This is fairly surprising, the Concourse team develops on Mac...

**Comment by bvandewalle** [comment]
I had to relogin recently and it worked without an issue. So I guess I cannot reproduce ;-)

**Comment by clarafu** [comment]
Possibly a butchered or extremely old `~/.flyrc`? Closing for now, but you can reopen if you run into this issue again.
