### ISSUE TITLE
fly should not panic

### ISSUE THREAD

**Issue by challiwill** [concourse/fly#45]
When the user does not specify a job while hijacking fly panics:

`` fly -t target -j pipeline `` results in:

![screen shot 2015-12-02 at 9 44 13 am](https://cloud.githubusercontent.com/assets/1977612/11545866/95f181fa-98fe-11e5-98e8-330cd22ce4bc.png)

**Comment by nitram509** [comment]
Hi,

there is one more case, when ```fly``` crashes.
Simply run ```fly watch -j foobar``` will trigger the following

```
$> concourse-java-maven-test-prj git:(master) fly watch -j foobar                       
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/concourse/fly/commands/internal/flaghelpers.(*JobFlag).UnmarshalFlag(0x727fd8, 0x7fff5fbff945, 0x6, 0x0, 0x0)
	/var/vcap/packages/fly/src/github.com/concourse/fly/commands/internal/flaghelpers/job_flag.go:19 +0x3f5
github.com/jessevdk/go-flags.convertUnmarshal(0x7fff5fbff945, 0x6, 0x4369e0, 0x727fd8, 0x16, 0x16, 0x0, 0x0)
	/var/vcap/packages/fly/src/github.com/jessevdk/go-flags/convert.go:157 +0x176
github.com/jessevdk/go-flags.convertUnmarshal(0x7fff5fbff945, 0x6, 0x4614a0, 0x727fd8, 0xd9, 0x8, 0x0, 0x0)
	/var/vcap/packages/fly/src/github.com/jessevdk/go-flags/convert.go:162 +0x2ab
github.com/jessevdk/go-flags.convert(0x7fff5fbff945, 0x6, 0x4614a0, 0x727fd8, 0xd9, 0x5893a0, 0x60, 0xc820015e90, 0x0, 0x0)
	/var/vcap/packages/fly/src/github.com/jessevdk/go-flags/convert.go:173 +0x79
github.com/jessevdk/go-flags.(*Option).set(0xc8200ec480, 0xc8200b39d0, 0x0, 0x0)
	/var/vcap/packages/fly/src/github.com/jessevdk/go-flags/option_private.go:41 +0x5e9
github.com/jessevdk/go-flags.(*Parser).parseOption(0xc820010af0, 0xc820089560, 0xc8200f46b0, 0x1, 0xc8200ec480, 0x1, 0x0, 0x0, 0x0)
	/var/vcap/packages/fly/src/github.com/jessevdk/go-flags/parser_private.go:186 +0x642
github.com/jessevdk/go-flags.(*Parser).parseShort(0xc820010af0, 0xc820089560, 0x7fff5fbff943, 0x1, 0x0, 0x0, 0x0)
	/var/vcap/packages/fly/src/github.com/jessevdk/go-flags/parser_private.go:256 +0x203
github.com/jessevdk/go-flags.(*Parser).ParseArgs(0xc820010af0, 0xc82000a250, 0x3, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0)
	/var/vcap/packages/fly/src/github.com/jessevdk/go-flags/parser.go:232 +0xf54
github.com/jessevdk/go-flags.(*Parser).Parse(0xc820010af0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/var/vcap/packages/fly/src/github.com/jessevdk/go-flags/parser.go:154 +0x9b
main.main()
	/var/vcap/packages/fly/src/github.com/concourse/fly/main.go:14 +0x62

goroutine 5 [runnable]:
os/signal.loop()
	/var/vcap/data/packages/golang/08f1cb1a11d32468882fc07a0d5b33fd735ddda4-7bd95b94d3d9f1caa3ade1fcd770a507f9bcef23/src/os/signal/signal_unix.go:20
created by os/signal.init.1
	/var/vcap/data/packages/golang/08f1cb1a11d32468882fc07a0d5b33fd735ddda4-7bd95b94d3d9f1caa3ade1fcd770a507f9bcef23/src/os/signal/signal_unix.go:28 +0x37
```
