### ISSUE TITLE
`fly execute ...` panics when setting the output directory for a task with no outputs

### ISSUE THREAD

**Issue by alidaka** [concourse/fly#51]
We're setting up a new task in our pipeline which _will_ have an output but _currently doesn't_. For one-off testing, we have been using a command like:
`fly -t foo execute --config=task.yml --input=source=. --output=artifact=./tmp`

This succeeds when `--output` is not specified (although task.yml does specify an output with the same name). But with it, most of the way through our command's output in the terminal, we get:

```
panic: unexpected EOF

goroutine 36 [running]:
github.com/concourse/fly/commands/internal/executehelpers.Download(0x7fff5fbffbac, 0x5, 0x820a8c240, 0x35, 0x820a747e0, 0x24, 0x820a437a0)
    /var/vcap/packages/fly/src/github.com/concourse/fly/commands/internal/executehelpers/downloads.go:45 +0x6de
...
```

Clearly this was user error, but a meaningful error message would be great here.

**Comment by alidaka** [comment]
We now know the output actually exists, and we're still seeing the panic message.

**Comment by mmb** [comment]
We also see this panic when a long running task with an output fails:

task.sh:
```sh
#!/bin/sh
sleep 60
exit 1
```

task.yml:
```yaml
---
platform: linux
image: docker:///busybox
inputs:
- name: task-repo
outputs:
- name: output1
run:
  path: task-repo/tasks/test/task.sh
```

```
fly \
  -t private \
  execute \
  -c task.yml \
  -i task-repo=../.. \
  -o output1=/tmp/output

executing build 61206
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  200k    0  200k    0     0   368k      0 --:--:-- --:--:-- --:--:--  371k
initializing with docker:///busybox
running task-repo/tasks/test/task.sh
panic: unexpected EOF

goroutine 55 [running]:
panic(0x4bb800, 0xc82000e150)
	/var/vcap/data/packages/golang/74a08cab924ada0966290d7426c2f5dd47e3966e.1-bd7b819a67fc06537a11961cb26814db6e46cf77/src/runtime/panic.go:464 +0x3e6
github.com/concourse/fly/commands/internal/executehelpers.Download(0xa23170, 0xc82011e680, 0x7fff5fbff839, 0x7, 0x7fff5fbff841, 0xb, 0xc8203506c0, 0x24, 0xc82036e0f0, 0x50, ...)
	/var/vcap/packages/fly/src/github.com/concourse/fly/commands/internal/executehelpers/downloads.go:34 +0x5fc
github.com/concourse/fly/commands.(*ExecuteCommand).Execute.func2(0xa23170, 0xc82011e680, 0x7fff5fbff839, 0x7, 0x7fff5fbff841, 0xb, 0xc8203506c0, 0x24, 0xc82036e0f0, 0x50, ...)
	/var/vcap/packages/fly/src/github.com/concourse/fly/commands/execute.go:103 +0x48
created by github.com/concourse/fly/commands.(*ExecuteCommand).Execute
	/var/vcap/packages/fly/src/github.com/concourse/fly/commands/execute.go:107 +0xa21
```

Remove the -o option to `fly execute` and it fails correctly:

```
fly \
  -t private \
  execute \
  -c task.yml \
  -i task-repo=../..

executing build 61207
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  200k    0  200k    0     0   487k      0 --:--:-- --:--:-- --:--:--  492k
initializing with docker:///busybox
running task-repo/tasks/test/task.sh
failed
```

/cc @mandyozhao

**Comment by chendrix** [comment]
Moved to concourse/concourse#1086
