### ISSUE TITLE
panic

### ISSUE THREAD

**Issue by challiwill** [concourse/fly#86]
Looks like we got a panic when trying to download an output:

```
$fly -t ci e -c task.yml -i input1=. -i input2=out.tar -o output=/tmp/output
targeting https://cli.ci.cf-app.com

executing build 1064
could not create tar stream: could not run tar: fork/exec /usr/bin/tar: not a directory
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  221M    0  221M    0     0  8445k      0 --:--:--  0:00:26 --:--:-- 11.0M
  0     0    0     0    0     0      0      0 --:--:--  0:00:59 --:--:--     0panic: unexpected EOF

goroutine 40 [running]:
panic(0x4c9600, 0xc82000e180)
    /var/vcap/data/packages/golang/69f4e820bb43cb872465d0829e4dbadf45bce46d.1-79e1f854e3d9185a248e448c6135eb17728bf934/src/runtime/panic.go:464 +0x3e6
github.com/concourse/fly/commands/internal/executehelpers.Download(0xa952c0, 0xc82012c8e0, 0x7fff5fbfed1d, 0xb, 0x7fff5fbfed29, 0x10, 0xc8202f63c0, 0x24, 0xc820334140, 0x4b, ...)
    /var/vcap/packages/fly/src/github.com/concourse/fly/commands/internal/executehelpers/downloads.go:34 +0x5fc
github.com/concourse/fly/commands.(*ExecuteCommand).Execute.func2(0xa952c0, 0xc82012c8e0, 0x7fff5fbfed1d, 0xb, 0x7fff5fbfed29, 0x10, 0xc8202f63c0, 0x24, 0xc820334140, 0x4b, ...)
    /var/vcap/packages/fly/src/github.com/concourse/fly/commands/execute.go:103 +0x48
created by github.com/concourse/fly/commands.(*ExecuteCommand).Execute
    /var/vcap/packages/fly/src/github.com/concourse/fly/commands/execute.go:107 +0xa26
```

I'm not sure if the output destination has to exist, but that could be the issue because `/tmp/output` does not.

**Comment by challiwill** [comment]
Does this mean we aren't properly creating the output?

**Comment by vito** [comment]
Concourse version?

**Comment by challiwill** [comment]
1.2.0

**Comment by jeffpak** [comment]
I've noticed that we see no panic if the input is not a tar/tgz. That's perplexing to me though because our pipeline job uses a .tgz as a resource for the task we're trying to execute.

**Comment by jfrank-pivotal** [comment]
We're seeing this as well (v1.3.0).  This looks like the same issue as #51.  The `execute` has 3 inputs and 1 output.  It happens both with and without an absolute path, and with and without the target output directory existing.  The directory is correctly created prior to the panic.

We ran `fly sync` to ensure we were up to date, but it had no effect.

The panic is coming from here: https://github.com/concourse/fly/blob/95d704cf580cac748e4475998aad4ad76eaf5aaa/commands/internal/executehelpers/downloads.go#L34.

Here's the full output:
```
# fly -t <target> execute -c <task yml> -i <input 1 name>=<input 1 path> -i <input 2 name>=<input 2 path> -i <input 3 name>=<input 3 path> -o <output name>=<output path> [crashes with and without -x]
targeting <our Concourse URL>

executing build 3986
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 78.4M    0 78.4M    0     0  1673k      0 --:--:--  0:00:48 --:--:-- 3002k
100  670k    0  670k    0     0  14255      0 --:--:--  0:00:48 --:--:--  172k
100 73.1M    0 73.1M    0     0  1297k      0 --:--:--  0:00:57 --:--:-- 7139kpanic: unexpected EOF

goroutine 27 [running]:
panic(0x4c8ac0, 0xc820014150)
	/var/vcap/data/packages/golang/69f4e820bb43cb872465d0829e4dbadf45bce46d.1-5976994459bcc9ff5681862098c6d6ba3ae0d8d5/src/runtime/panic.go:464 +0x3e6
github.com/concourse/fly/commands/internal/executehelpers.Download(0xa54170, 0xc820107630, 0x7fff5fbffa4e, 0x15, 0x7fff5fbffa64, 0x40, 0xc82032abd0, 0x24, 0xc82005dc20, 0x5b, ...)
	/var/vcap/packages/fly/src/github.com/concourse/fly/commands/internal/executehelpers/downloads.go:34 +0x5fc
github.com/concourse/fly/commands.(*ExecuteCommand).Execute.func2(0xa54170, 0xc820107630, 0x7fff5fbffa4e, 0x15, 0x7fff5fbffa64, 0x40, 0xc82032abd0, 0x24, 0xc82005dc20, 0x5b, ...)
	/var/vcap/packages/fly/src/github.com/concourse/fly/commands/execute.go:103 +0x48
created by github.com/concourse/fly/commands.(*ExecuteCommand).Execute
	/var/vcap/packages/fly/src/github.com/concourse/fly/commands/execute.go:107 +0xa22
```

We have been seeing the interrupted curl uploads (invalid magic) like #46 on this deployment as well, so it may be related to that, especially given the `unexpected EOF` showing up at the end there.

**Comment by jfrank-pivotal** [comment]
FYI, we're still seeing this 100% of the time in v1.4.1 as well on an execute with -j, one -i, and one -o.

**Comment by glestaris** [comment]
I believe it may have to do with the task image. I was consistently occurring with alpine and golang:1.7 but not with busybox.

**Comment by vito** [comment]
This is likely a timeout that occurs with a load balancer in the middle. If the task takes longer than the load balancer's idle timeouts, the downloads will have their connection interrupted.

**Comment by cjcjameson** [comment]
Bump -- we've stopped trying to run `fly execute` with `--output` because it panics so frequently, Just tried to do it again (Concourse v2.5.0 on a BOSH deployment) and it failed.

```
panic: tar extract failed (unexpected EOF). output: ""

goroutine 37 [running]:
panic(0x40e480, 0xc42035a080)
	/usr/local/Cellar/go/1.7.1/libexec/src/runtime/panic.go:500 +0x1a1
github.com/concourse/fly/commands/internal/executehelpers.Download(0x68e700, 0xc420161c80, 0x7fff5fbffa4c, 0x12, 0x7fff5fbffa5f, 0x1f, 0xc4203ea450, 0x24, 0xc4203ee1e0, 0x59, ...)
	/Users/pilot/Worker/workdir/containers/000018vtuq0/tmp/build/a9832f70/concourse/src/github.com/concourse/fly/commands/internal/executehelpers/downloads.go:30 +0x1c3
github.com/concourse/fly/commands.(*ExecuteCommand).Execute.func2(0x68e700, 0xc420161c80, 0x7fff5fbffa4c, 0x12, 0x7fff5fbffa5f, 0x1f, 0xc4203ea450, 0x24, 0xc4203ee1e0, 0x59, ...)
	/Users/pilot/Worker/workdir/containers/000018vtuq0/tmp/build/a9832f70/concourse/src/github.com/concourse/fly/commands/execute.go:106 +0x7d
created by github.com/concourse/fly/commands.(*ExecuteCommand).Execute
	/Users/pilot/Worker/workdir/containers/000018vtuq0/tmp/build/a9832f70/concourse/src/github.com/concourse/fly/commands/execute.go:110 +0x89c
```

**Comment by ashb** [comment]
I just got this happening on v2.6.0 trying to test my change to a PR i'm opening for the docker-image-resource.

Is there a work around for this?

**Comment by benmoss** [comment]
I am seeing this on 2.7.0 as well

```
$ fly -t ci execute -c $PWD/build.yml -i output=$PWD -o binary=/tmp/
executing build 233658
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  162M    0  162M    0     0  11.4M      0 --:--:--  0:00:14 --:--:-- 13.3M
initializing
panic: tar extract failed (unexpected EOF). output: ""

goroutine 41 [running]:
panic(0x41d6c0, 0xc4203af770)
	/usr/local/Cellar/go/1.7.1/libexec/src/runtime/panic.go:500 +0x1a1
github.com/concourse/fly/commands/internal/executehelpers.Download(0x6a5bc0, 0xc42017bd20, 0x7fff5fbff99e, 0x6, 0x7fff5fbff9a5, 0xa, 0xc420368b10, 0x24, 0xc4203981e0, 0x50, ...)
	/Users/pilot/Worker/workdir/containers/00002te877v/tmp/build/a9832f70/concourse/src/github.com/concourse/fly/commands/internal/executehelpers/downloads.go:30 +0x1c3
github.com/concourse/fly/commands.(*ExecuteCommand).Execute.func2(0x6a5bc0, 0xc42017bd20, 0x7fff5fbff99e, 0x6, 0x7fff5fbff9a5, 0xa, 0xc420368b10, 0x24, 0xc4203981e0, 0x50, ...)
	/Users/pilot/Worker/workdir/containers/00002te877v/tmp/build/a9832f70/concourse/src/github.com/concourse/fly/commands/execute.go:107 +0x7d
created by github.com/concourse/fly/commands.(*ExecuteCommand).Execute
	/Users/pilot/Worker/workdir/containers/00002te877v/tmp/build/a9832f70/concourse/src/github.com/concourse/fly/commands/execute.go:111 +0x89c
```

**Comment by chendrix** [comment]
Moved to concourse/concourse#1091

**Comment by chendrix** [comment]
Moved to concourse/concourse#1092
